homepage/urls.py
from django.contrib import admin
from django.urls import path
from .views import(
    index,
    schedule_create,
    schedule,
    schedule_delete,
    schedule_detail

)



app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
    path('create/', schedule_create.as_view(success_url='/schedule/'),name='form' ),
    path('schedule/',schedule.as_view(),name='schedule_list'),
    path('schedule/<int:pk>/delete/',schedule_delete.as_view(success_url='/schedule/'),name='schedule_delete'),
    path('schedule/<int:pk>', schedule_detail, name='schedule_detail')
]

story4/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Schedule(models.Model):
    
    day_choices = [
        ('Senin','Senin'),
        ('Selasa','Selasa'),
        ('Rabu','Rabu'),
        ('Kamis','Kamis'),
        ('Jumat','Jumat'),
        ('Sabtu','Sabtu'),
        ('Minggu','Minggu')
    ]

    category_choices = [
        ('Study','Study'),
        ('Event', 'Event'),
        ('Work', 'Work'),
        ('Gaming', 'Gaming'),
        ('Sport', 'Sport'),
        ('Organization', 'Organization')
    ]

    activity = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    day = models.CharField(max_length=10,choices=day_choices,default='Sun')
    date = models.DateTimeField(auto_now=False, auto_now_add=False)
    category = models.CharField(max_length=20,choices=category_choices,default='St')    
    class Meta:
        ordering = ['-date']

    def get_absolute_url(self):
        return reverse('schedule_detail', kwargs={'pk': self.pk})


# Create your models here.

homepage/forms.py
from django import forms
from .models import Schedule

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].widget.attrs.update({'placeholder': 'Format: YYYY-MM-DD HH:MM'})

homepage/views.py
from django.shortcuts import render
from django.views.generic import DeleteView,ListView, DetailView, CreateView
from .models import Schedule
from .forms import ScheduleForm

# Create your views here.
def index(request):
    return render(request, 'index.html')

    
class schedule_create(CreateView):
    model = Schedule
    form_class = ScheduleForm
    template_name = 'CreateSchedule.html'
    context = 'form'
    
class schedule(ListView):
    model = Schedule
    qs = Schedule.objects.all()
    context_obj_name = 'Schedule'
    template_name = "jadwal.html"

class schedule_delete(DeleteView):
    model = Schedule
    template_name = 'delete.html'

class schedule_detail(DetailView):
    model = Schedule
    template_name = 'detail.html' 

homepage/templates/CreateSchedule.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Dana - Buat Schedule</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="{% static 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <style>
    body{background :#EADD89
    }

  </style>

  </head>
  <body>
    <!-- NAVIGATION -->
    <div class="w3-top">
      <div class="w3-bar w3-black">
        <span class="branding w3-bar-item w3-mobile">Fauzan Pradana</span>
        <span class="w3-right w3-mobile">
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="{% url 'homepage:index'%}">Home</a>
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="{% url 'homepage:form' %}">Schedule</a>
        </span>
      </div>
    </div>

    {% load crispy_forms_tags %}
<section class="section">
  <div id = "sekat">
    <!-- <img src="img/logologi.png"> -->
  </div>
<div class="page pb-0">
    <div class="w3-container w3-center">
        <h2 class="header">Buat Schedule</h2>
        <form method="POST" action=".">
            {% csrf_token %}
            <div class="row">
                <div class="w3-container w3-center">
                    {{ form.activity|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="w3-col m6">
                    <p>{{ form.category|as_crispy_field }}</p>
                </div>
                <div class="col-md-6">
                    {{ form.place|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    {{ form.day|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.date|as_crispy_field }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
</section>


  </body>
</html>

homepage/templates/delete.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Dana - hapus Schedule</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="{% static 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <style>
    body{background :#EADD89
    }

  </style>

  </head>
  <body>
    <!-- NAVIGATION -->
    <div class="w3-top">
      <div class="w3-bar w3-black">
        <span class="branding w3-bar-item w3-mobile">Fauzan Pradana</span>
        <span class="w3-right w3-mobile">
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="{% url 'homepage:index'%}">Home</a>
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="{% url 'homepage:form' %}">Schedule</a>
        </span>
      </div>
    </div>

    {% block content %}
    <div id = "sekat">
      <!-- <img src="img/logologi.png"> -->
    </div>
<div class="container content-font">
    <h2 class="header"> Are you sure you want to delete the following:</h2>
    <p>{{ object.activity }}</p>
    <form method="POST">
        {% csrf_token %}
        <button class="btn btn-danger">Yes, delete</button>
    </form>
</div>
{% endblock %}

</body>
</html>

homepage/templates/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Dana - Schedule</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="{% static 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <style>
    body{background :#EADD89
    }

  </style>

  </head>
  <body>
    <!-- NAVIGATION -->
    <div class="w3-top">
      <div class="w3-bar w3-black">
        <span class="branding w3-bar-item w3-mobile">Fauzan Pradana</span>
        <span class="w3-right w3-mobile">
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="{% url 'homepage:index'%}">Home</a>
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="{% url 'homepage:form' %}">Schedule</a>
        </span>
      </div>
    </div>
    {% block content %}
    <div id = "sekat">
      <!-- <img src="img/logologi.png"> -->
    </div>
    <div class="container">
        <div class="square" id="jadwal">
            <div class="card" style="color: #212121">
                <div class="card-body">
                    <h5 class="card-title">{{object.category}}</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">Due Date: {{ object.day }} {{ object.date }}</h6>
                    <p class="card-text">
                        Will be held in {{ object.place }} <br>
                        My Activity is {{ object.activity }}
                    </p>
                    <a href="{% url 'homepage:schedule_delete' object.id %}" class="btn btn-warning">Delete</a>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}


</body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>PPW Story 3</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="{% static 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  </head>
  <body>
    <!-- NAVIGATION -->
    <div class="w3-top">
      <div class="w3-bar w3-black">
        <span class="branding w3-bar-item w3-mobile">Fauzan Pradana</span>
        <span class="w3-right w3-mobile">
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="#about">About</a>
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="#hobbies">Hobbies</a>
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="#experience">Experience</a>
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="#works">Works</a>
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="#contact">Contact</a>
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="{% url 'homepage:form' %}">Schedule</a>
        </span>
      </div>
    </div>

    <!-- SHOWCASE -->
    <section class="showcase">
      <div class="w3-container w3-center">
        <hh>
        <hh>
        <p class="w3-animate-opacity">Hi, I'm</p>
        <hr>
        <h1 class="w3-text-shadow w3-animate-opacity">Fauzan Pradana</h1>
        <hr>
        <h2 class="w3-animate-opacity">NPM : 1806205281</h2>

      </div>
    </section>

<div id = "logo">
  <!-- <img src="img/logologi.png"> -->
</div>

<!-- ABOUT -->
<section id="about" class="section">
  <div class="w3-container w3-center">
        <h1 class="w3-text-shadow">---------- Get to Know Me ----------</h1>
  </div>

  <div class="w3-container">
    <div class="w3-row-padding">
      <div class="w3-col m5">
        <div class="image">
          <img src="{% static 'img/fotoprofil.jpg' %}"class="w3-circle" alt="Alps" id="profpic">
        </div>
      </div>
      <div class="bio w3-col m7">
        <div id="bio" class="w3-container w3-show">
          <h3>3 Agustus 1999</h3>
          <p>Salam kenal, Panggil saja Dana. seorang Mahasiswa Ilmu Komputer yang sedang berusaha untuk mengembangkan diri</p>
        </div>
      </div>
    </div>
  </div>

  <!-- HOBBIES -->
  <section id="hobbies" class="section">
    <div class="w3-container w3-center">
          <h1 class="w3-text-shadow">---------- Some of My Hobbies ----------</h1>
    </div>

    <div class="w3-container">
      <div class="w3-row-padding">
        <div class="w3-col m5">
          <div class="image2">
            <img src="{% static 'img/bb.jpg' %}" class="w3-round-xlarge" alt="Norway" style="width:35vw" id="profpic2">
        </div>
      </div>
      <div class="bio w3-col m7">
        <div class="image2">
          <img src="{% static 'img/milan.jpg' %}" class="w3-round-xlarge" alt="Norway" style="width:35vw" id="profpic2">
        </div>
      </div>
    </div>

    <div class="w3-row-padding">
      <div class="w3-col m5">
        <div class="image2">
          <img src="{% static 'img/vg.jpg' %}" class="w3-round-xlarge" alt="Norway" style="width:35vw" id="profpic2">
      </div>
    </div>
    <div class="bio w3-col m7">
      <div class="image2">
        <img src="{% static 'img/novel.jpg' %}" class="w3-round-xlarge" alt="Norway" style="width:35vw" id="profpic2">
      </div>
    </div>
  </div>
  </div>

  <div id = "sekat">
    <!-- <img src="img/logologi.png"> -->
  </div>


  <!-- EXPERIENCE -->
  <section id="experience" class="section">
    <div class="w3-container w3-center">
          <h1 class="w3-text-shadow">---------- Activities & Skills ----------</h1>
    </div>

    <div class="w3-container">
      <div class="w3-row-padding">
        <div class="w3-col m5">
          <div class="image2">
            <img src="{% static 'img/compfest.jpg' %}" class="w3-round-xlarge" alt="Norway" style="width:35vw" id="profpic2">
        </div>
      </div>
      <div class="exp w3-col m7">
        <div id="exp" class="w3-container w3-show">
          <h3> </h3>
          <p>Seminar Compfest</p>
        </div>
      </div>
    </div>

    <div class="w3-row-padding">
      <div class="w3-col m5">
        <div class="image2">
          <img src="{% static 'img/humas.jpg' %}" class="w3-round-xlarge" alt="Norway" style="width:35vw" id="profpic2">
      </div>
    </div>
    <div class="exp w3-col m7">
      <div id="exp" class="w3-container w3-show">
        <h3> </h3>
        <p>Humas BEM Fasilkom</p>
      </div>
    </div>
  </div>

  <div class="w3-row-padding">
    <div class="w3-col s4">
      <div class = "image2">
      <img src="{% static 'img/piton.png' %}" style="width:auto" class="w3-round-xlarge" alt="Norway" id="profpic3">
      </div>
    </div>
    <div class="w3-col s4">
      <div class = "image2">
      <img src="{% static 'img/cpp.png' %}" style="width:auto" class="w3-round-xlarge" alt="Norway" id="profpic3">
    </div>
    </div>
    <div class="w3-col s4">
      <div class = "image2">
      <img src="{% static 'img/java.png' %}" style="width:auto" class="w3-round-xlarge" alt="Norway" id="profpic3">
    </div>
    </div>
  </div>

  </div>

  <div id = "sekat">
    <!-- <img src="img/logologi.png"> -->
  </div>

  <!-- CONTACT -->
  <section id="works" class="section">
    <div class="w3-container w3-center">
          <h1 class="w3-text-shadow">---------- Click My Works ! ----------</h1>
    </div>

    <div class="w3-row-padding">
      <div class="w3-col s4">
        <div class = "image2">
        <a href="http://kekatastore.com/produk/jujur-atau-berani2" target="_blank"><img src="{% static 'img/juber.jpg' %}" style="width:auto" class="w3-round-xlarge" alt="Norway" id="profpic5"></a>
        </div>
      </div>
      <div class="w3-col s4">
        <div class = "image2">
        <a href="https://www.instagram.com/fpradana3/" target="_blank"><img src="{% static 'img/ig.jpg' %}" style="width:auto" class="w3-round-xlarge" alt="Norway" id="profpic5"></a>
      </div>
      </div>
      <div class="w3-col s4">
        <div class = "image2">
        <a href="https://www.wattpad.com/user/AceLatif" target="_blank"><img src="{% static 'img/cinta.jpg' %}" style="width:auto" class="w3-round-xlarge" alt="Norway" id="profpic5"></a>
      </div>
      </div>
    </div>

    <div id = "sekat">
      <!-- <img src="img/logologi.png"> -->
    </div>

    <!-- WORKS -->
    <section id="contact" class="section">
      <div class="w3-container w3-center">
            <h5 class="w3-text-shadow">Let’s get in touch!</h5>
      </div>

      <div id = "kontak" style="display : flex" >
        <a href="https://www.instagram.com/fpradana3/" target="_blank"><img src="{% static 'img/insta.png' %}" style="width :13vw"  class="center"></a>
        <a href="https://www.linkedin.com/in/fauzan-pradana-364906186/" target="_blank"><img src="{% static 'img/link.png' %}" style="width : 13vw" class="center"></a>
      </div>


</section>
  </body>
</html>

homepage/templates/jadwal.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Dana - Schedule</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="{% static 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <style>
    body{background :#EADD89
    }

  </style>

  </head>
  <body>
    <!-- NAVIGATION -->
    <div class="w3-top">
      <div class="w3-bar w3-black">
        <span class="branding w3-bar-item w3-mobile">Fauzan Pradana</span>
        <span class="w3-right w3-mobile">
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="{% url 'homepage:index'%}">Home</a>
          <a class="w3-bar-item w3-button w3-mobile w3-hover-blue" href="{% url 'homepage:form' %}">Schedule</a>
        </span>
      </div>
    </div>

{% block content %}
<div id = "sekat">
  <!-- <img src="img/logologi.png"> -->
</div>
<div class="container">
    <h2 class="header">My Schedule</h2>
    <div class="square" id="jadwal">
        <div class="row">
            {% for object in object_list %}
            <div class="col-md-4 mx-auto">
                <form action="." method="POST">
                {% csrf_token %}
                <div class="card" style="color: #212121; margin-bottom: 1%">
                    <div class="card-body special-font">
                        <h5 class="card-title">{{object.category}}</a></h5>
                        <h6 class="card-subtitle mb-2 text-muted">Due Date: {{ object.day }} {{ object.date }}</h6>
                        <p class="card-text">
                            Will be held in {{ object.place }} <br>
                            My Activity is {{ object.activity }}
                        </p>
                        <a href="{% url 'homepage:schedule_delete' object.id %}" class="btn btn-warning">Delete</a>
                    </div>
                </div>
            </div>
            </form>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

</body>
</html>